In [3]:
import pandas as pd
pd.set_option("display.max_columns", None)
df = pd.read_csv('2016.csv')
df = pd.read_csv('2017.csv')
df = pd.read_csv('2018.csv')

In [4]:
df.head()

,RptNo,RptName,StatCourseNo,StatCourseName,DataDate,PlaceNo,PlaceName,PeriodNo,PeriodName,Complex1,ComplexName,Complex2,Complex2Name,Complex3,Complex3Name,Complex4,Complex4Name,Complex5,Complex5Name,DeriveNo,DeriveExplain,FValue,SValue,RptDeptNo,RptDeptName,CreateTime,ModifyTime
0,10440-01-04-2,臺中市國民小學教育經費支出(預、決算數),1044001a007,國民小學教育經費支出(預、決算數)-預算數(單位:元),2018/1/1 上午 12:00:00,10000066000,臺中市,Y,年,2300100001,公立,230040000101,人事費,0,NaN,0,NaN,0,NaN,0,NaN,1.560703e+10,NaN,387040000E,教育局,2019/1/23 上午 09:56:21,2019/1/29 下午 01:01:01
1,10440-01-04-2,臺中市國民小學教育經費支出(預、決算數),1044001a007,國民小學教育經費支出(預、決算數)-預算數(單位:元),2018/1/1 上午 12:00:00,10000066000,臺中市,Y,年,2300100002,私立,230040000101,人事費,0,NaN,0,NaN,0,NaN,0,NaN,4.553881e+08,NaN,387040000E,教育局,2019/1/23 上午 09:56:21,2019/1/29 下午 01:01:01
2,10440-01-04-2,臺中市國民小學教育經費支出(預、決算數),1044001a007,國民小學教育經費支出(預、決算數)-預算數(單位:元),2018/1/1 上午 12:00:00,10000066000,臺中市,Y,年,2300100001,公立,230040000103,退休撫卹,0,NaN,0,NaN,0,NaN,0,NaN,2.462806e+09,NaN,387040000E,教育局,2019/1/23 上午 09:56:21,2019/1/29 下午 01:01:01
3,10440-01-04-2,臺中市國民小學教育經費支出(預、決算數),1044001a007,國民小學教育經費支出(預、決算數)-預算數(單位:元),2018/1/1 上午 12:00:00,10000066000,臺中市,Y,年,2300100002,私立,230040000103,退休撫卹,0,NaN,0,NaN,0,NaN,0,NaN,2.184562e+07,NaN,387040000E,教育局,2019/1/23 上午 09:56:21,2019/1/29 下午 01:01:01
4,10440-01-04-2,臺中市國民小學教育經費支出(預、決算數),1044001a007,國民小學教育經費支出(預、決算數)-預算數(單位:元),2018/1/1 上午 12:00:00,10000066000,臺中市,Y,年,2300100001,公立,230040000102,經常支出_其他,0,NaN,0,NaN,0,NaN,0,NaN,1.034058e+09,NaN,387040000E,教育局,2019/1/23 上午 09:56:21,2019/1/29 下午 01:01:01

In [6]:
temp = df[['ComplexName','Complex2Name', 'FValue']]
temp

   ComplexName Complex2Name        FValue
0           公立          人事費  1.560703e+10
1           私立          人事費  4.553881e+08
2           公立         退休撫卹  2.462806e+09
3           私立         退休撫卹  2.184562e+07
4           公立      經常支出_其他  1.034058e+09
5           私立      經常支出_其他  2.565858e+08
6           公立         資本支出  7.600470e+08
7           私立         資本支出  4.145126e+07
8           公立          人事費  1.564987e+10
9           私立          人事費  4.172253e+08
10          公立         退休撫卹  2.571501e+09
11          私立         退休撫卹  2.101962e+07
12          公立      經常支出_其他  9.510185e+08
13          私立      經常支出_其他  2.436094e+08
14          公立         資本支出  5.743368e+08
15          私立         資本支出  3.207200e+07

In [7]:
Type = temp.groupby(['ComplexName','Complex2Name'])['FValue'].sum().reset_index()
Type['year'] = 2017
Type

  ComplexName Complex2Name        FValue  year
0          公立          人事費  3.125690e+10  2017
1          公立      經常支出_其他  1.985076e+09  2017
2          公立         資本支出  1.334384e+09  2017
3          公立         退休撫卹  5.034307e+09  2017
4          私立          人事費  8.726134e+08  2017
5          私立      經常支出_其他  5.001952e+08  2017
6          私立         資本支出  7.352326e+07  2017
7          私立         退休撫卹  4.286524e+07  2017

In [8]:
df2016 = pd.read_csv('2016.csv')
df2017 = pd.read_csv('2017.csv')
df2018 = pd.read_csv('2018.csv')

new = df2016[['ComplexName','Complex2Name', 'FValue']].groupby(['ComplexName','Complex2Name'])['FValue'].sum().reset_index()
new['year'] = 2016
new

  ComplexName Complex2Name        FValue  year
0          公立          人事費  3.266950e+10  2016
1          公立      經常支出_其他  1.430186e+09  2016
2          公立         資本支出  1.084894e+09  2016
3          私立          人事費  8.407491e+08  2016
4          私立      經常支出_其他  4.837973e+08  2016
5          私立         資本支出  1.377015e+08  2016

In [9]:
frames = [Type, new]

result = pd.concat(frames)
result

  ComplexName Complex2Name        FValue  year
0          公立          人事費  3.125690e+10  2017
1          公立      經常支出_其他  1.985076e+09  2017
2          公立         資本支出  1.334384e+09  2017
3          公立         退休撫卹  5.034307e+09  2017
4          私立          人事費  8.726134e+08  2017
5          私立      經常支出_其他  5.001952e+08  2017
6          私立         資本支出  7.352326e+07  2017
7          私立         退休撫卹  4.286524e+07  2017
0          公立          人事費  3.266950e+10  2016
1          公立      經常支出_其他  1.430186e+09  2016
2          公立         資本支出  1.084894e+09  2016
3          私立          人事費  8.407491e+08  2016
4          私立      經常支出_其他  4.837973e+08  2016
5          私立         資本支出  1.377015e+08  2016